# Created by Gematron (Gematron studios)
# given to Missplaced crew member; Present

command uc.version():
  permission: op
  trigger:
    send "V2.2 (Sky bata)"

### Join and leave system ###

on join:
	set join message to "<dark gray>[<green>+<dark gray>] %player%"

on quit:
	set leave message to "<dark gray>[<red>-<dark gray>] %player%"

on death:
  if attacker is a player:
    if {Investigation} is true:
      set death message to "<dark gray>[<red>⚔<dark gray>] ?????????? got killed by ????????????"
    else:
      set death message to "<dark gray>[<red>⚔<dark gray>] %death-message%"
  else:
    if {Investigation} is true:
      set death message to "<dark gray>[<red>☠<dark gray>] ?????????? got killed"
    else:
      set death message to "<dark gray>[<red>☠<dark gray>] %death-message%"


### life system ###
# system to register memer to the event automaticly
on join:
  if {First_Time_Joined::*} does not contain uuid of player:
    add uuid of player to {First_Time_Joined::*}
    set {Lives.%uuid of player%} to 10

command uc.time_reset():
  permission: op
  trigger:
    set {timer_seconds_globle} to 0
    set {timer_min_globle} to 0
    set {timer_houer_globle} to 0

every 1 second:
  add 1 to {timer_seconds_globle}
  if {timer_seconds_globle} is equal to 60:
    set {timer_seconds_globle} to 0
    add 1 to {timer_min_globle}
  if {timer_min_globle} is equal to 60:
    set {timer_min_globle} to 0
    add 1 to {timer_houer_globle}

command uc.time():
  trigger:
    send "%{timer_houer_globle}%:%{timer_min_globle}%:%{timer_seconds_globle}% / 2:30:0"

# duisplaying the number of lives the user has once joined
on join:
  apply blindness without any particles whilst hiding the potion icon to the player for 1 seconds
  apply darkness without any particles whilst hiding the potion icon to the player for 2 seconds
  set player's gamemode to survival
  execute console command "/ppo %player% reset"
  if {Lives.%uuid of player%} = 10: 
    send title "" with subtitle "<purple> %{Lives.%uuid of player%}%💖" to player for 2 seconds with fadein 0 second and fade out 1 second
  if {Lives.%uuid of player%} = 9 or 8: 
    send title "" with subtitle "<blue> %{Lives.%uuid of player%}%💖" to player for 2 seconds with fadein 0 second and fade out 1 second
  if {Lives.%uuid of player%} = 7 or 6: 
    send title "" with subtitle "<light green> %{Lives.%uuid of player%}%💖" to player for 2 seconds with fadein 0 second and fade out 1 second
  if {Lives.%uuid of player%} = 5 or 4: 
    send title "" with subtitle "<dark green> %{Lives.%uuid of player%}%💖" to player for 2 seconds with fadein 0 second and fade out 1 second
  if {Lives.%uuid of player%} = 3 or 2: 
    send title "" with subtitle "<yellow> %{Lives.%uuid of player%}%💖" to player for 2 seconds with fadein 0 second and fade out 1 second
  if {Lives.%uuid of player%} = 1: 
    send title "" with subtitle "<red> %{Lives.%uuid of player%}%💖" to player for 2 seconds with fadein 0 second and fade out 1 second
  if {Lives.%uuid of player%} = 0 or -1: 
    set {Lives.%uuid of player%} to 0
    send title "" with subtitle "<gray> %{Lives.%uuid of player%}%💖" to player for 2 seconds with fadein 0 second and fade out 1 second
    set player's gamemode to spectator
  if {Lives.%uuid of player%} = -100: 
    set player's gamemode to spectator
    set the player's display name to "<orange>[DEV] %name of player%"
    set the player's tab list name to "<orange>[DEV] %name of player%"
    execute console command "/team join DEV %player%"
  if {player.DeathAnnimation.%uuid of player%} is true:
    loop 60 times:
      teleport the player to {respawn%player%}
      wait 1 tick
  set {player.DeathAnnimation.%uuid of player%} to false
  set the maximum health of the player to 10

# removing a life if a person died
on death:
  set {Lives.%uuid of victim%} to {Lives.%uuid of victim%} - 1

# duisplaying the number of lives the user has once respawned
on respawn:
  if {Lives.%uuid of player%} = 10: 
    send action bar "<purple> %{Lives.%uuid of player%}%💖" to player
  if {Lives.%uuid of player%} = 9 or 8: 
    send action bar "<blue> %{Lives.%uuid of player%}%💖" to player
  if {Lives.%uuid of player%} = 7 or 6: 
    send action bar "<light green> %{Lives.%uuid of player%}%💖" to player
  if {Lives.%uuid of player%} = 5 or 4: 
    send action bar "<dark green> %{Lives.%uuid of player%}%💖" to player
  if {Lives.%uuid of player%} = 3 or 2: 
    send action bar "<yellow> %{Lives.%uuid of player%}%💖" to player
  if {Lives.%uuid of player%} = 1: 
    send action bar "<red> %{Lives.%uuid of player%}%💖" to player
  if {Lives.%uuid of player%} = 0 or -1: 
    set {Lives.%uuid of player%} to 0
    send action bar "<gray> %{Lives.%uuid of player%}%💖" to player
    
# resets all varavbles inside of the game
command uc.reset_game():
  permission: op
  trigger:
    Broadcast "Server will restart in 5 seconds"
    wait 5 seconds
    delete {First_Time_Joined::*}
    delete {Lives.%uuid of player%}
    delete {player.LastChance.%uuid of player%}
    restart server

# displayes all info and there lives
command uc.Lives_info():
  permission: op
  trigger:
    send "<green>[======== [INFO] ========]"
    loop all players:
      send "[🏷%loop-player%][📎%uuid of loop-player%][ 💖%{Lives.%uuid of loop-player%}%]"
    send "<green>[======================]"

# command to set all of there lives
command uc.set.lives.number() <player> <integer>:
  permission: op
  trigger:
    execute console command "/team leave %uuid of arg-1%"
    set {Lives.%uuid of arg-1%} to arg-2
    send "[🏷%arg-1%][📎%uuid of arg-1%][ 💖%{Lives.%uuid of arg-1%}%]"
    if {Lives.%uuid of arg-1%} = 10: 
      set the arg-1's display name to "<purple>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      set the arg-1's tab list name to "<purple>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      execute console command "/team join 10 %uuid of arg-1%"
    if {Lives.%uuid of arg-1%} = 9 or 8: 
      set the arg-1's display name to "<blue>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      set the arg-1's tab list name to "<blue>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      execute console command "/team join 9-8 %uuid of arg-1%"
    if {Lives.%uuid of arg-1%} = 7 or 6: 
      set the arg-1's display name to "<dark green>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      set the arg-1's tab list name to "<dark green>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      execute console command "/team join 7-6 %uuid of arg-1%"
    if {Lives.%uuid of arg-1%} = 5 or 4: 
      set the arg-1's display name to "<light green>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      set the arg-1's tab list name to "<light green>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      execute console command "/team join 5-4 %uuid of arg-1%"
    if {Lives.%uuid of arg-1%} = 3 or 2: 
      set the arg-1's display name to "<yellow>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      set the arg-1's tab list name to "<yellow>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      execute console command "/team join 3-2 %uuid of arg-1%"
    if {Lives.%uuid of arg-1%} = 1: 
      set the arg-1's display name to "<red>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      set the arg-1's tab list name to "<red>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      execute console command "/team join 1 %uuid of arg-1%"
    if {Lives.%uuid of arg-1%} = 0 or -1: 
      set {Lives.%uuid of arg-1%} to 0
      set the arg-1's display name to "<gray>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
      set the arg-1's tab list name to "<gray>[💖 %{Lives.%uuid of arg-1%}%] %arg-1%"
    if {Lives.%uuid of arg-1%} = -100:
      execute console command "/team join DEV %uuid of arg-1%"
      set the arg-1's display name to "<orange>[DEV] %arg-1%"
      set the arg-1's tab list name to "<orange>[DEV] %arg-1%"

# upodate live conunter when respawning   
on respawn:
  wait 0.2 second
  if player is a player:
    execute console command "/team leave %player%"
  if player is a player:
    if {Lives.%uuid of player%} = 10: 
      set the player's display name to "<purple>[💖 %{Lives.%uuid of player%}%] %name of player%"
      set the player's tab list name to "<purple>[💖 %{Lives.%uuid of player%}%] %name of player%"
      execute console command "/team join 10 %player%"
    if {Lives.%uuid of player%} = 9 or 8: 
      set the player's display name to "<blue>[💖 %{Lives.%uuid of player%}%] %name of player%"
      set the player's tab list name to "<blue>[💖 %{Lives.%uuid of player%}%] %name of player%"
      execute console command "/team join 9-8 %player%"
    if {Lives.%uuid of player%} = 7 or 6: 
      set the player's display name to "<dark green>[💖 %{Lives.%uuid of player%}%] %name of player%"
      set the player's tab list name to "<dark green>[💖 %{Lives.%uuid of player%}%] %name of player%"
      execute console command "/team join 7-6 %player%"
    if {Lives.%uuid of player%} = 5 or 4: 
      set the player's display name to "<light green>[💖 %{Lives.%uuid of player%}%] %name of player%"
      set the player's tab list name to "<light green>[💖 %{Lives.%uuid of player%}%] %name of player%"
      execute console command "/team join 5-4 %player%"
    if {Lives.%uuid of player%} = 3 or 2: 
      set the player's display name to "<yellow>[💖 %{Lives.%uuid of player%}%] %name of player%"
      set the player's tab list name to "<yellow>[💖 %{Lives.%uuid of player%}%] %name of player%"
      execute console command "/team join 3-2 %player%"
    if {Lives.%uuid of player%} = 1: 
      set the player's display name to "<red>[💖 %{Lives.%uuid of player%}%] %name of player%"
      set the player's tab list name to "<red>[💖 %{Lives.%uuid of player%}%] %name of player%"
      execute console command "/team join 1 %player%"
    if {Lives.%uuid of player%} = 0 or -1: 
      set {Lives.%uuid of player%} to 0
      set the player's display name to "<gray>[💖 %{Lives.%uuid of player%}%] %name of player%"
      set the player's tab list name to "<gray>[💖 %{Lives.%uuid of player%}%] %name of player%"
    if {Lives.%uuid of player%} = -100:
      set the player's display name to "<orange>[DEV] %name of player%"
      set the player's tab list name to "<orange>[DEV] %name of player%"

# sets in statuses once people join
on join:
  wait 0.2 second
  if player is a player:
    execute console command "/team leave %player%"
  if {Lives.%uuid of player%} = 10: 
    set the player's display name to "<purple>[💖 %{Lives.%uuid of player%}%] %name of player%"
    set the player's tab list name to "<purple>[💖 %{Lives.%uuid of player%}%] %name of player%"
    execute console command "/team join 10 %player%"
  if {Lives.%uuid of player%} = 9 or 8: 
    set the player's display name to "<blue>[💖 %{Lives.%uuid of player%}%] %name of player%"
    set the player's tab list name to "<blue>[💖 %{Lives.%uuid of player%}%] %name of player%"
    execute console command "/team join 9-8 %player%"
  if {Lives.%uuid of player%} = 7 or 6: 
    set the player's display name to "<dark green>[💖 %{Lives.%uuid of player%}%] %name of player%"
    set the player's tab list name to "<dark green>[💖 %{Lives.%uuid of player%}%] %name of player%"
    execute console command "/team join 7-6 %player%"
  if {Lives.%uuid of player%} = 5 or 4: 
    set the player's display name to "<light green>[💖 %{Lives.%uuid of player%}%] %name of player%"
    set the player's tab list name to "<light green>[💖 %{Lives.%uuid of player%}%] %name of player%"
    execute console command "/team join 5-4 %player%"
  if {Lives.%uuid of player%} = 3 or 2: 
    set the player's display name to "<yellow>[💖 %{Lives.%uuid of player%}%] %name of player%"
    set the player's tab list name to "<yellow>[💖 %{Lives.%uuid of player%}%] %name of player%"
    execute console command "/team join 3-2 %player%"
  if {Lives.%uuid of player%} = 1: 
    set the player's display name to "<red>[💖 %{Lives.%uuid of player%}%] %name of player%"
    set the player's tab list name to "<red>[💖 %{Lives.%uuid of player%}%] %name of player%"
    execute console command "/team join 1 %player%"
  if {Lives.%uuid of player%} = 0 or -1:
    set {Lives.%uuid of player%} to 0
    set the player's display name to "<gray>[💖 %{Lives.%uuid of player%}%] %name of player%"
    set the player's tab list name to "<gray>[💖 %{Lives.%uuid of player%}%] %name of player%"
  if {Lives.%uuid of player%} = -100:
    set the player's display name to "<orange>[DEV] %name of player%"
    set the player's tab list name to "<orange>[DEV] %name of player%"

### death animations ###
# setting the players location to there death location
on death:
  set {death%victim%} to victim's location

# respawn animation
on respawn:
  wait 0.1 seconds
  if {player.LastChance.%uuid of player%} is true:
    set {player.LastChance.%uuid of player%} to false
    apply mining fatigue 255 without any particles whilst hiding the potion icon to the player for 60 seconds
    send title "" with subtitle "" to player for 1 seconds with fadein 0 second and fade out 0 second
    teleport the player to {death%player%}
    execute console command "/ppo %player% reset"
    apply resistance 255 without any particles whilst hiding the potion icon to the player for 25 seconds
    teleport the player 25 blocks above the player's location
    set {DeathSpawn::%player's uuid%} to location of event-player
    teleport the player 25 blocks below the player's location
    set pitch of {DeathSpawn::%player's uuid%} to 90
    execute console command "/ppo %player% add small_gust chains"
    execute console command "/ppo %player% trial_spawner_detection_ominous sphere"
    execute console command "/ppo %player% add soul_fire_flame invocation"
    execute console command "/ppo %player% add soul_fire_flame icosphere"
    execute console command "/ppo %player% add ominous_spawning sphere"
    loop 30 times:
      teleport the player to {death%player%}
      wait 1 tick
    play 400 campfire cosy smoke with offset of 4, 0, 4 and speed 0.00001 at location of player
    strike lightning effect at the player
    loop 20 times:
      teleport the player to {death%player%}
      wait 1 tick
    strike lightning effect at the player
    loop 10 times:
      teleport the player to {death%player%}
      wait 1 tick
    strike lightning effect at the player
    loop 5 times:
      teleport the player to {death%player%}
      wait 1 tick
    play 400 campfire cosy smoke with offset of 4, 0, 4 and speed 0.00001 at location of player
    execute console command "/ppo %player% add raid_omen icosphere"
    loop 20 times:
      wait 1 ticks
      strike lightning effect at the player
      teleport the player to {death%player%}
    loop 20 times:
      wait 1 ticks
      strike lightning effect at the player
      strike lightning effect at the player
      play 600 campfire cosy smoke with offset of 6, 0, 6 and speed 0.00001 at location of player
      play 6000 soul fire flame with offset of 1, 12, 1 and speed 0.001 at location of player
      teleport the player to {death%player%}
    send title "" with subtitle "<red>☠" to player for 10 seconds with fadein 5 second and fade out 1 second
    loop 20 times:
      wait 1 ticks
      strike lightning effect at the player
      strike lightning effect at the player
      strike lightning effect at the player
      strike lightning effect at the player
      strike lightning effect at the player
      strike lightning effect at the player
      strike lightning effect at the player
      strike lightning effect at the player
      play 900 campfire cosy smoke with offset of 8, 0, 8 and speed 0.00001 at location of player
      play 6000 soul fire flame with offset of 1, 16, 1 and speed 0.1 at location of player
      play 50 campfire cosy smoke with offset of 8, 4, 8 and speed 0.3 at location of player
      teleport the player to {death%player%}
    play 7000 campfire cosy smoke with offset of 8, 4, 8 and speed 1 at location of player
    play 60000 soul fire flame with offset of 4, 16, 4 and speed 1 at location of player
    play 6000 soul fire flame with offset of 0, 0, 0 and speed 1.5 at location of player
    execute console command "/ppo %player% reset"
    push the player upwards at speed 4
    wait 6 ticks
    set player's gamemode to spectator
    loop 60 times:
      teleport the player to {DeathSpawn::%player's uuid%}
      wait 1 tick
    apply darkness without any particles whilst hiding the potion icon to the player for 15 seconds
    send action bar "<red>%player% Died" to player
    loop 200 times:
      teleport the player to {DeathSpawn::%player's uuid%}
      wait 1 tick
    apply blindness without any particles whilst hiding the potion icon to the player for 5 seconds
    loop 80 times:
      teleport the player to {DeathSpawn::%player's uuid%}
      wait 1 tick
    execute console command "/ppo %player% reset"
    set {Lives.%uuid of player%} to 0
    set the maximum health of the player to 10
    kick the player due to "<black>[ 💖 ]<red> You ran out of lives;<white> You can now spectate people; from this point onwards you can not enter the compotition"
    broadcast "<dark gray><bold>[<black>💖<dark gray>] %player% ran out of lives"
                              
  else if {Lives.%uuid of player%} = 0:
    if {investigation.1} contains uuid of player:
      clear {investigation.1}
    if {investigation.2} contains uuid of player:
      clear {investigation.2}
    if {investigation.3} contains uuid of player:
      clear {investigation.3}
    if {The_hourde::*} contains uuid of player:
      remove uuid of player from {The_hourde::*}
    apply resistance 255 without any particles whilst hiding the potion icon to the player for 5 seconds
    apply mining fatigue 255 without any particles whilst hiding the potion icon to the player for 60 seconds
    set {player.LastChance.%uuid of player%} to true
    set the maximum health of the player to 1
    execute console command "/ppo %player% add flame chains"
    execute console command "/ppo %player% add flame cube"
    execute console command "/ppo %player% add flame vortex"
    execute console command "/ppo %player% add flame whirl"
    send title "" with subtitle "<purple>🔗" to player for 100 seconds with fadein 0 second and fade out 1 second
    loop 1100 times:
      if {player.LastChance.%uuid of player%} is true:
        teleport the player to {death%player%}
        wait 1 tick
    if {player.LastChance.%uuid of player%} is true:
      send title "" with subtitle "<purple>5" to player for 100 seconds with fadein 0 second and fade out 1 second
      loop 20 times:
        teleport the player to {death%player%}
        wait 1 tick
    if {player.LastChance.%uuid of player%} is true:
      send title "" with subtitle "<purple>4" to player for 100 seconds with fadein 0 second and fade out 1 second
      loop 20 times:
        teleport the player to {death%player%}
        wait 1 tick
    if {player.LastChance.%uuid of player%} is true:
      send title "" with subtitle "<purple>3" to player for 100 seconds with fadein 0 second and fade out 1 second
      loop 20 times:
        teleport the player to {death%player%}
        wait 1 tick
    if {player.LastChance.%uuid of player%} is true:
      send title "" with subtitle "<purple>2" to player for 100 seconds with fadein 0 second and fade out 1 second
      loop 20 times:
        teleport the player to {death%player%}
        wait 1 tick
    if {player.LastChance.%uuid of player%} is true:
      send title "" with subtitle "<purple>1" to player for 100 seconds with fadein 0 second and fade out 1 second
      loop 20 times:
        teleport the player to {death%player%}
        wait 1 tick
    if {player.LastChance.%uuid of player%} is true:
      kill the player
                              
  else:
    set {player.DeathAnnimation.%uuid of player%} to true
    set player's gamemode to spectator
    set {respawn%player%} to player's location
    apply invisibility without any particles whilst hiding the potion icon to the player for 2 seconds
    apply darkness without any particles whilst hiding the potion icon to the player for 7 seconds
    apply resistance 255 without any particles whilst hiding the potion icon to the player for 10 seconds
    apply mining fatigue 255 without any particles whilst hiding the potion icon to the player for 3 seconds
    send title "" with subtitle "<red>☠" to player for 4 seconds with fadein 0 second and fade out 2 second
    loop 40 times:
      teleport the player to {death%player%}
      wait 1 tick
    apply Blindness without any particles whilst hiding the potion icon to the player for 3 seconds
    loop 30 times:
      teleport the player to {death%player%}
      wait 1 tick
    execute console command "/ppo %player% reset"
    set player's gamemode to survival
    apply invisibility without any particles whilst hiding the potion icon to the player for 1 seconds
    wait 5 tick
    loop 30 times:
      teleport the player to {respawn%player%}
      wait 1 tick
    set {player.DeathAnnimation.%uuid of player%} to false

# if player is chaned and disconnecs and reconects; they auto die
on join:
  if {player.LastChance.%uuid of player%} is true:
    set {player.LastChance.%uuid of player%} to false
    kill the player
    set the maximum health of the player to 10
                              
### events ###
# activating events
command uc.set.event() <integer>:
  permission: op
  trigger:
    set {Disasters} to false
    set {all_hunters} to false
    set {around_the_world} to false
    set {tasks} to false
    set {worldboss} to false
    set {investigation} to false
    set {the_horde} to false
    set {tutorial} to false
    set {the_Border} to false
    set {helth_regen} to false
    if arg-1 is equal to 0:
      send action bar "All events reset" to player
    if arg-1 is equal to 3:
      set {Disasters} to true
      send action bar "Disasters" to player
    if arg-1 is equal to 1:
      set {all_hunters} to true
      send action bar "<light red>All hunters" to player
    if arg-1 is equal to 2:
      set {around_the_world} to true
      send action bar "<red>Around the world" to player
    if arg-1 is equal to 4:
      set {tasks} to true
      send action bar "<blue>Tasks" to player
    if arg-1 is equal to 5:
      set {worldboss} to true
      send action bar "<red>Worldboss" to player
    if arg-1 is equal to 6:
      set {investigation} to true
      set {helth_regen} to true
      send action bar "<purple>Investigation" to player
    if arg-1 is equal to 7:
      set {the_horde} to true
      send action bar "<green>The Horde" to player
    if arg-1 is equal to 8:
      set {the_Border} to true
      set {all_hunters} to true
      send action bar "<black>The Border" to player
    wait 3 seconds
    send action bar "Ready to start event; to start run command /uc.Start_round()" to player
# display insidemation to what event is on or off
command uc.event.info():
  permission: op
  trigger:
    send "<green>[======== [INFO] ========]"
    send "[🏷Disasters][💫 %{Disasters}%]"
    send "[🏷all_hunters][💫 %{all_hunters}%]"
    send "[🏷around_the_world][💫 %{around_the_world}%]"
    send "[🏷tasks][💫 %{tasks}%]"
    send "[🏷worldboss][💫 %{worldboss}%]"
    send "[🏷the the_horde][💫 %{the_horde}%]"
    send "[🏷investigation][💫 %{investigation}%]"
    send "[🏷the Borde][💫 %{the_Border}%]"
    send "[🏷helth regen][💫 %{helth_regen}%]"
    send "<green>[========================]"
                              
# start the round
command uc.Start_round():
  permission: op
  trigger:
    send action bar "<yellow> Starting round soon..." to player
    wait 4 seconds
    send title "" with subtitle "<yellow> Sesion Started" to all players for 2 seconds with fadein 0 second and fade out 1 second
    execute console command "/uc.time_reset()"
    wait 30 seconds
    if {all_hunters} is true:
      make console execute command "uc.all_hunters.start(DNR)"
    else:
      make console execute command "uc.hunters.start(DNR)"
    wait 30 seconds
    if {around_the_world} is true:
      make console execute command "uc.around_the_world.start(DNR)"
    if {tasks} is true:
      make console execute command "uc.tasks.start(DNR)"
    if {worldboss} is true:
      make console execute command "uc.world_boss.start(DNR)"
    if {the_horde} is true:
      make console execute command "uc.The_hourde.start(DNR)"
    if {investigation} is true:
      make console execute command "uc.investigation(DNR)"
    if {the_Border} is true:
      make console execute command "uc.border(DNR)"
    if {Disasters} is true:
      make console execute command "uc.disastors.start(DNR)"
    if {helth_regen} is true:
      wait 10 seconds
      broadcast "<blue><bold>==========<white>{Event}<blue>=========="
      broadcast "- players with a high ammout of lives will not be able to regenerate helth"
                              
# end the round
command uc.end_round():
  permission: op
  trigger:
    set {soul_link} to false
    set {around_the_world} to false
    set {the_Border} to false
    set {Disasters} to false
    send action bar "<yellow> Compleating final preperations and ending server..." to player
    wait 2 seconds
    if {tasks} is true:
      loop all players:
        send action bar "<white> tasks are gowing to explode soon" to loop-player
      wait 2 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 9 seconds" to loop-player
        if {compleated::*} does not contain uuid of loop-player:
          execute console command "/ppo %loop-player% add enchant popper"
          execute console command "/ppo %loop-player% add poof pulse"
      wait 1 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 8 seconds" to loop-player
      wait 1 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 7 seconds" to loop-player
      wait 1 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 6 seconds" to loop-player
      wait 1 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 5 seconds" to loop-player
      loop all players:
        if {compleated::*} does not contain uuid of loop-player:
          execute console command "/ppo %loop-player% add ominous_spawning icosphere"
          execute console command "/ppo %loop-player% add add soul_fire_flame quadhelix"
          execute console command "/ppo %loop-player% add soul_fire_flame invocation"
      wait 1 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 4 seconds" to loop-player
      wait 1 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 3 seconds" to loop-player
      wait 1 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 2 seconds" to loop-player
      wait 1 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 1 seconds" to loop-player
      loop all players:
        if {compleated::*} does not contain uuid of loop-player:
          apply darkness without any particles whilst hiding the potion icon to the player for 4 seconds
          execute console command "/ppo %loop-player% add dragon_breath outline"
      wait 1 seconds
      loop all players:
        send action bar "<white> Tasks will explode in 0 seconds" to loop-player
        if {compleated::*} does not contain uuid of loop-player:
          play 20000 dragon breath with offset of 0.01, 0.01, 0.01 and speed 1 at loop-player's location
          execute console command "/ppo %loop-player% reset %loop-player%"
          kill the loop-player
    if {the_horde} is true:
      clear {all_uuids::*}
      loop all players:
        if loop-player's gamemode is not spectator:
          add loop-player's uuid to {all_uuids::*}
      if size of {all_uuids::*} is equal to size of {The_hourde::*}:
        send title "" with subtitle "<green><light green>🧟 The              🧟" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<green>🧟 The <light green>Infected     🧟" to all players for 3 seconds with fadein 0 second and fade out 1 second
        wait 2 seconds
        send title "" with subtitle "<green>🧟 The Infected <light green>Won 🧟" to all players for 2 seconds with fadein 0 second and fade out 1 second
      else:
        send title "" with subtitle "<green><light green>🧟 The              🧟" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<green>🧟 The <light green>Infected     🧟" to all players for 3 seconds with fadein 0 second and fade out 1 second
        wait 2 seconds
        send title "" with subtitle "<green>🧟 The Infected <light green>Lost 🧟" to all players for 2 seconds with fadein 0 second and fade out 1 second
    if {worldboss} is true:
      set {worldBoss::L6} to false
      set {worldBoss::L5} to false
      set {worldBoss::L4} to false
      set {worldBoss::L3} to false
      set {worldBoss::L2} to false
      set {worldBoss::L1} to false
      set {worldboss} to false
      set {_player} to ({current_worldboss} parsed as offline player)
      execute console command "/ppo %{_player}% reset"
      send title "" with subtitle "<red>░░░ ░░░░░ ░░░░ ░░" to all players for 2 seconds with fadein 0 second and fade out 1 second
      wait 0.25 seconds
      send title "" with subtitle "<red>T░░ w░░l░ ░o░░ i░" to all players for 2 seconds with fadein 0 second and fade out 1 second
      wait 0.25 seconds
      send title "" with subtitle "<red>Th░ wo░ld ░os░ is" to all players for 2 seconds with fadein 0 second and fade out 1 second
      wait 0.25 seconds
      send title "" with subtitle "<red>The World Boss is" to all players for 2 seconds with fadein 0 second and fade out 1 second
      wait 3 seconds
      send title "" with subtitle "<red>%{_player}%" to all players for 2 seconds with fadein 0 second and fade out 1 second
    if {Investigation} is true:
      set {investigation} to false
      if {investigation.1} or {investigation.2} or {investigation.3} is set:
        send title "" with subtitle "<purple>                           █" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>                        █won" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>                      █e won" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>                   █have won" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>                █rs have won" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>             █ators have won" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>          █tigators have won" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>       █vestigators have won" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>    █ Investigators have won" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>█ The Investigators have won" to all players for 2 seconds with fadein 0 second and fade out 1 second
      else:
        send title "" with subtitle "<purple>                            █" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>                         █ost" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>                      █e lost" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>                   █have lost" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>                █rs have lost" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>             █ators have lost" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>          █tigators have lost" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>       █vestigators have lost" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>    █ Investigators have lost" to all players for 2 seconds with fadein 0 second and fade out 1 second
        wait 0.25 seconds
        send title "" with subtitle "<purple>█ The Investigators have lost" to all players for 2 seconds with fadein 0 second and fade out 1 second
    wait 10 seconds
    if {all_hunters} is true:
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> Contract failed" to loop-player
      wait 2 seconds
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [10s]" to loop-player
          execute console command "/ppo %loop-player% add dust beam red"
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [09s]" to loop-player
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [08s]" to loop-player
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [07s]" to loop-player
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [06s]" to loop-player
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [05s]" to loop-player
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [04s]" to loop-player
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [03s]" to loop-player
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [02s]" to loop-player
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [01s]" to loop-player
      wait 1 second
      loop all players:
        if {all_Hunters_list::*} contains uuid of loop-player:
          send action bar "<red> exacution in [00s]" to loop-player
          play 600 flame with offset of 1, 1, 1 and speed 0.1 at location of player
          execute console command "/ppo %loop-player% reset"
          kill loop-player
    else:
      set {_player} to ({hunter} parsed as offline player)
      execute console command "/ppo %{_player}% add dust beam red"
      send action bar "<red> Contract failed" to {_player}
      wait 2 seconds
      send action bar "<red> exacution in [10s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [09s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [08s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [07s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [06s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [05s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [04s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [03s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [02s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [01s]" to {_player}
      wait 1 second
      send action bar "<red> exacution in [00s]" to {_player}
      wait 1 second
      execute console command "/ppo %{_player}% reset"
      loop all players:
        if {_player} is loop-player:
          play 600 flame with offset of 1, 1, 1 and speed 0.1 at location of loop-player
      kill {_player}
    clear {current_worldboss} 
    clear {compleated::*}
    set {all_hunters} to false
    set {tasks} to false
    wait 50 seconds
    send title "" with subtitle "<yellow> Sesion Ended" to all players for 2 seconds with fadein 0 second and fade out 1 second